package vn.orderrecorder.shopee;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public final class XlsxExporter {
    private XlsxExporter(){}
    public static void write(OutputStream target,List<OrderRecord> source)throws IOException{List<OrderRecord>orders=new ArrayList<>(source==null?Collections.emptyList():source);orders.sort(Comparator.comparingLong(r->r.receivedAt));ZipOutputStream z=new ZipOutputStream(target);add(z,"[Content_Types].xml",contentTypes());add(z,"_rels/.rels",rootRels());add(z,"xl/workbook.xml",workbook());add(z,"xl/_rels/workbook.xml.rels",workbookRels());add(z,"xl/styles.xml",styles());add(z,"xl/worksheets/sheet1.xml",sheet(orders));z.finish();z.flush();}
    private static String sheet(List<OrderRecord>orders){String[]headers={"STT","Mã đơn hàng","SĐT","Thời gian nhận đơn"};StringBuilder s=new StringBuilder();s.append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetViews><sheetView workbookViewId=\"0\"><pane ySplit=\"1\" topLeftCell=\"A2\" activePane=\"bottomLeft\" state=\"frozen\"/></sheetView></sheetViews><cols><col min=\"1\" max=\"1\" width=\"7\" customWidth=\"1\"/><col min=\"2\" max=\"2\" width=\"20\" customWidth=\"1\"/><col min=\"3\" max=\"3\" width=\"18\" customWidth=\"1\"/><col min=\"4\" max=\"4\" width=\"28\" customWidth=\"1\"/></cols><sheetData><row r=\"1\">");for(int i=0;i<headers.length;i++)cell(s,col(i)+"1",headers[i],1);s.append("</row>");SimpleDateFormat f=new SimpleDateFormat("HH:mm:ss dd-MM-yyyy",Locale.getDefault());f.setTimeZone(TimeZone.getTimeZone("Asia/Ho_Chi_Minh"));int row=2,index=1;for(OrderRecord r:orders){s.append("<row r=\"").append(row).append("\">");cell(s,"A"+row,String.valueOf(index++),0);cell(s,"B"+row,r.businessOrderCode(),0);cell(s,"C"+row,TextParser.normalizePhone(r.receiverPhone),2);cell(s,"D"+row,r.receivedAt>0?f.format(new Date(r.receivedAt)):"",0);s.append("</row>");row++;}s.append("</sheetData><autoFilter ref=\"A1:D").append(Math.max(1,row-1)).append("\"/></worksheet>");return s.toString();}
    private static void cell(StringBuilder s,String ref,String value,int style){s.append("<c r=\"").append(ref).append("\" t=\"inlineStr\" s=\"").append(style).append("\"><is><t xml:space=\"preserve\">").append(xml(value)).append("</t></is></c>");}
    private static String col(int i){StringBuilder b=new StringBuilder();i++;while(i>0){i--;b.insert(0,(char)('A'+i%26));i/=26;}return b.toString();}
    private static String xml(String v){if(v==null)return"";return v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&apos;");}
    private static void add(ZipOutputStream z,String name,String text)throws IOException{z.putNextEntry(new ZipEntry(name));z.write(text.getBytes(StandardCharsets.UTF_8));z.closeEntry();}
    private static String contentTypes(){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/></Types>";}
    private static String rootRels(){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>";}
    private static String workbook(){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Đơn hàng\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>";}
    private static String workbookRels(){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/></Relationships>";}
    private static String styles(){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><numFmts count=\"1\"><numFmt numFmtId=\"164\" formatCode=\"@\"/></numFmts><fonts count=\"2\"><font><sz val=\"11\"/><name val=\"Calibri\"/></font><font><b/><sz val=\"11\"/><name val=\"Calibri\"/></font></fonts><fills count=\"2\"><fill><patternFill patternType=\"none\"/></fill><fill><patternFill patternType=\"gray125\"/></fill></fills><borders count=\"1\"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs><cellXfs count=\"3\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/><xf numFmtId=\"0\" fontId=\"1\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\"/><xf numFmtId=\"164\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyNumberFormat=\"1\"/></cellXfs></styleSheet>";}
}
